# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :production do
    gem 'sinatra', '~> 1.4', '>= 1.4.7'
    gem 'puma', '~> 5.6', '>= 5.6.4'
    gem 'tiny_tds', '~> 2.1', '>= 2.1.5'
    gem 'json', '~> 2.6', '>= 2.6.1'
end

group :development do
    gem 'dotenv', '~> 2.7', '>= 2.7.6'
    gem 'sinatra-reloader', '~> 1.0'
end
